import {
  IconRoad,
  IconHeartbeat,
  IconTrees,
  IconSchool,
  IconHeartHandshake,
  IconHelp,
  IconClipboardList,
  IconChartBar,
  IconUsers,
  IconMenu2,
  IconWorld,
  IconTrendingUp,
  IconTrendingDown,
  IconMinus,
  IconTicket,
  IconCheck,
  IconPercentage,
  IconClock,
  IconEdit,
  IconInbox,
  IconEye,
  IconCircleCheck,
  IconListDetails,
  IconAlertCircle,
  IconTools,
  IconAlertTriangle,
  IconCamera,
  IconX,
  IconTag,
  IconUserPlus,
  IconPlus,
  IconTimeline,
  IconThumbUp,
  IconLogin,
  IconFilter,
  IconLock,
  IconChevronDown,
  type Icon as TablerIconType,
  type IconProps,
} from '@tabler/icons-react'

const ICONS: Record<string, TablerIconType> = {
  road: IconRoad,
  heartbeat: IconHeartbeat,
  trees: IconTrees,
  school: IconSchool,
  'heart-handshake': IconHeartHandshake,
  help: IconHelp,
  'clipboard-list': IconClipboardList,
  'chart-bar': IconChartBar,
  users: IconUsers,
  'menu-2': IconMenu2,
  world: IconWorld,
  'trending-up': IconTrendingUp,
  'trending-down': IconTrendingDown,
  minus: IconMinus,
  ticket: IconTicket,
  check: IconCheck,
  percentage: IconPercentage,
  clock: IconClock,
  edit: IconEdit,
  inbox: IconInbox,
  eye: IconEye,
  'circle-check': IconCircleCheck,
  'list-details': IconListDetails,
  'alert-circle': IconAlertCircle,
  tools: IconTools,
  'alert-triangle': IconAlertTriangle,
  camera: IconCamera,
  x: IconX,
  tag: IconTag,
  'user-plus': IconUserPlus,
  plus: IconPlus,
  timeline: IconTimeline,
  'thumb-up': IconThumbUp,
  login: IconLogin,
  filter: IconFilter,
  lock: IconLock,
  'chevron-down': IconChevronDown,
}

interface AppIconProps extends IconProps {
  /** Nombre del ícono en kebab-case (mismo identificador que antes usaba `ti ti-{name}`) */
  name: string
}

export function Icon({ name, ...props }: AppIconProps) {
  const Component = ICONS[name] ?? IconHelp
  return <Component aria-hidden="true" {...props} />
}
